apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: terracore-prototype

resources:
  - persistent-volume-claim.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: terracore
      app.kubernetes.io/part-of: terracore-prototype
    includeSelectors: true

images:
  - name: terracore-app
    newName: ghcr.io/REPLACE_WITH_GITHUB_OWNER/terracore-prototype
    newTag: prototype
