apiVersion: v1
kind: Service
metadata:
  name: terracore
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: terracore
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
